export const taskDataKey = (username) => `jlcTaskData_${username}`;
export const getUsersKey = () => `jlcTaskUsers`;
export const defaultUsers = [
  "Anto",
  "Brian",
  "Esteban",
  "Jorge",
  "Maxi",
  "Pablo",
];
export const sectors = [
  "Acerma",
  "AlfaVet",
  "Almacenes",
  "Arrufo",
  "Banco Macro",
  "Baños",
  "Broalco",
  "Calidad",
  "Cámaras Polivalentes",
  "Camioneros",
  "CDR Rafaela",
  "Chacarita",
  "Comedor",
  "Cremería Local",
  "Dulcería",
  "Efluentes",
  "Expedicion de quesos",
  "Famiq",
  "Fraccionado leche en polvo",
  "Fundido",
  "Granger",
  "Guardia",
  "JLC",
  "La Anónima",
  "Laboratorio",
  "Larga Vida",
  "Maduración",
  "Mantequería",
  "Menara",
  "Nanofiltración",
  "Oficinas",
  "PAER",
  "Planta 4 leche en polvo",
  "Planta 5 leche en polvo",
  "El Trébol",
  "Productos frescos",
  "Quesería de blandos",
  "Rafaela",
  "Rallado",
  "Recibo",
  "Red Gama",
  "Rezagos",
  "Sala de máquinas",
  "Santa Fe",
  "Saputo",
  "Servicio médico",
  "Taller JLC",
  "Taller de mantenimiento Ilolay",
  "Verónica",
  "Vio Banda",
];
